#!/bin/bash

#source /home/zeus/ARM_linux-phone/boot-talker/toolchains/tests/u-boot/voltron/dbgentry.py
#source gdbi.py
#source out/peda/peda.py
#
# use:  $ gdb -iex 'add-auto-load-safe-path .'
# loc:  $ gdb -x out/peda/peda.py out/test1_dbg
# any:  $ gdb -x out/.gdbinit
#

#        cat << 'EOF' > /etc/resolv.conf
#nameserver 192.168.0.101
#nameserver 8.8.8.8
#EOF

case $1 in
  "init")
        rm -rf .gdbinit
        ln -s out/.gdbinit .gdbinit
    ;;
  "ngdb")
        rm -rf .gdbinit
        ln -s out/.gdbinit .gdbinit
    ;;
  "peda")
        rm -rf .gdbinit
        cat << 'EOF' > .gdbinit
source out/peda/peda.py
EOF
    ;;
  *)
    echo ""
    echo "  Usage:  gdbinit [ init | ngdb | edbg |  ]"
    echo ""
    echo "And run:  gdb -iex 'add-auto-load-safe-path .'"
    echo ""
    ;;
esac
